### ISSUE TITLE
Adding space between items - alignment & arrangement

### ISSUE THREAD

**Issue by ienground** [touchlane/gridpad-android#27]
Hello, thanks to your library, shapes of grid are very awesome.
However, is it possible to add space between items : by columns / by rows.
in addition, I hope that we can adjust arrangement items in gridpad.
example) Arrangement.Center : < space > <item><item><item> <space>

Thanks for reading this issue!

**Comment by landarskiy** [comment]
Hello and thank you for your interest in the library!
We take into account your suggestions for further development, but we do not promise that they will be integrated soon.
As a solution to request alignment, you can always wrap your composable in Box, and that should work well and fast enough thanks to compose's internal optimizations.

**Comment by ienground** [comment]
Thanks for your answer! I hope these functions will be available soon. :)
so is it correct that spaces are not available in this version?
I checked, thanks ;)

**Comment by landarskiy** [comment]
That's right, the current version is not designed to do anything other than correctly partition the surface into cells based on your configuration (rows/columns count, rows/columns sizes).
